### PR TITLE
Update to AsyncKeyedLock 6.0.5

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Allowing actionable options, bug fixes with regards to timeouts, better error handling, minor optimizations, improved documentation, added considerably more tests.

### CODE REVIEW

**Comment by erlendoksvoll** [comment]
Hi! Thank you for showing an interest and creating a PR - unfortunately we will not start using your library at this time, but when our needs get more complex we will surely consider it again :)

**Comment by MarkCiliaVincenti** [comment]
@erlendoksvoll you are already using the library. This is a simple update to the latest version as well as a small constructor call change.

**Comment by erlendoksvoll** [comment]
Hi,  @MarkCiliaVincenti - it seems my Christmas cleanup was a little hasty - I will leave this until the new year when everyone is back. Thanks for contributing and have a great Christmas! :)

**Comment by MarkCiliaVincenti** [comment]
A Merry Christmas and a happy New year to you!

**Pull request merged**
