### PR TITLE
Like-for-like replacement of KeyedLock with AsyncKeyedLock library.

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Made a like-for-like replacement of the KeyedLock with a more performant AsyncKeyedLock library. You may want to review the pool size or remove it altogether, but I left it with the value of 10 to be just like KeyedLock was.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@elsand

**Comment by MarkCiliaVincenti** [comment]
@elsand

**Comment by MarkCiliaVincenti** [comment]
Oops sorry about that @elsand, realized I hadn't actually hit the save button on the changes I did, you can see them now. Once more, I'm not sure if you want to add an [Obsolete] to KeyedLock.

**Comment by elsand** [comment]
> I've re-implemented KeyedLock using AsyncKeyedLocker internally

Very nice, thanks :)

> I'm not sure if you want to add an [Obsolete] to KeyedLock.

Yes, that's a good idea.

**Comment by MarkCiliaVincenti** [comment]
> > I've re-implemented KeyedLock using AsyncKeyedLocker internally
> 
> Very nice, thanks :)
> 
> > I'm not sure if you want to add an [Obsolete] to KeyedLock.
> 
> Yes, that's a good idea.

OK, done. Over to you to merge.

**Comment by MarkCiliaVincenti** [comment]
@elsand

**Pull request merged**
